using Google.RECaptcha.Internazionalization;

namespace Google.RECaptcha
{
    public enum ReCaptchaLanguage
    {
        [Language("ar")] Arabic,
        [Language("bn")] Bengali,
        [Language("bg")] Bulgarian,
        [Language("ca")] Catalan,
        [Language("zh-CN")] ChineseSimplified,
        [Language("zh-TW")] ChineseTraditional,
        [Language("hr")] Croatian,
        [Language("cs")] Czech,
        [Language("da")] Danish,
        [Language("nl")] Dutch,
        [Language("en-GB")] EnglishUk,
        [Language("en")] EnglishUs,
        [Language("et")] Estonian,
        [Language("fil")] Filipino,
        [Language("fi")] Finnish,
        [Language("fr")] French,
        [Language("fr-CA")] FrenchCanadian,
        [Language("de")] German,
        [Language("gu")] Gujarati,
        [Language("de-AT")] GermanAustria,
        [Language("de-CH")] GermanSwitzerland,
        [Language("el")] Greek,
        [Language("iw")] Hebrew,
        [Language("hi")] Hindi,
        [Language("hu")] Hungarain,
        [Language("id")] Indonesian,
        [Language("it")] Italian,
        [Language("ja")] Japanese,
        [Language("kn")] Kannada,
        [Language("ko")] Korean,
        [Language("lv")] Latvian,
        [Language("lt")] Lithuanian,
        [Language("ms")] Malay,
        [Language("ml")] Malayalam,
        [Language("mr")] Marathi,
        [Language("no")] Norwegian,
        [Language("fa")] Persian,
        [Language("pl")] Polish,
        [Language("pt")] Portuguese,
        [Language("pt-BR")] PortugueseBrazil,
        [Language("pt-PT")] PortuguesePortugal,
        [Language("ro")] Romanian,
        [Language("ru")] Russian,
        [Language("sr")] Serbian,
        [Language("sk")] Slovak,
        [Language("sl")] Slovenian,
        [Language("es")] Spanish,
        [Language("es-419")] SpanishLatinAmerica,
        [Language("sv")] Swedish,
        [Language("ta")] Tamil,
        [Language("te")] Telugu,
        [Language("th")] Thai,
        [Language("tr")] Turkish,
        [Language("uk")] Ukrainian,
        [Language("ur")] Urdu,
        [Language("vi")] Vietnamese
    }
}